Apple website Clone
defoebrand/apple-clone pull request #2
Opened 2020-06-18 15:14 UTC by KartheekWD

This project consists of building a webpage using images as a background and adding gradients to elements. The goal is to make a clone of an old version of the Apple website.

2020-06-18 20:55 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-18 21:11 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @KartheekWD @defoebrand** 
Amazing job with your first submission for this project :muscle:  
Your page really looks like the original :clap: :clap: :clap:  
Your project is almost perfect.There are just a couple of details to improve before you can go ahead:
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload you ave 1 issue according to the validator.
- [ ] move the four images inside your main tag.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-18 21:11 UTC, andresporras3423 commented on index.html
> +	</section>
You should move this section inside the main tag

2020-06-19 09:35 UTC, peterrobert approved these changes
### APPROVED :clap: :+1: :partying_face: 
**HELLO** :wave: **you have done such an impressive job**. Your readme file is descriptive. Your pull request looks amazing.  This is very impressive work :clap: 

You have also implemented the changes requested by the previous review :clap: 

**On to the next project**
### HAPPY CODING :computer:

2020-06-19 10:00 UTC, merged